name: parselyzer
description: Parse `dart analyze --format=json` output into Dart objects.
homepage: https://github.com/Rexios80/parselyzer
version: 0.1.3

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^7.1.0
  collection: ^1.17.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  rexios_lints: ^9.2.0
  test: ^1.21.0
