name: parselyzer
description: Parse `dart analyze --format=json` output into Dart objects.
homepage: https://github.com/Rexios80/parselyzer
version: 0.1.1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  analyzer: ^5.5.0
  collection: ^1.17.1
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  rexios_lints: ^5.0.0
  test: ^1.21.0
